In [4]:
import pandas as pd

In [29]:
df.groupby("Department")["Salary"].max()

Department
HR       60000
IT       60000
Sales    60000
Name: Salary, dtype: int64

In [30]:
df.groupby("Department")["Salary"].sum()

Department
HR       310000
IT       360000
Sales    300000
Name: Salary, dtype: int64

In [31]:
df.groupby("Department")["Employee"].count()

Department
HR       7
IT       8
Sales    7
Name: Employee, dtype: int64

In [32]:
df.groupby("Department")[["Salary","Experience"]].mean()

                  Salary  Experience
Department
HR          44285.714286    3.142857
IT          45000.000000    2.750000
Sales       42857.142857    2.714286

#Merge & join

In [36]:
import pandas as pd

df1 = pd.DataFrame({
    "ID":[1,2,3,4],
    "Name":["A","B","C","D"]
})

df2 = pd.DataFrame({
    "ID":[3,4,5,6],
    "Salary":[30000,40000,50000,60000]
})

In [37]:
pd.merge(df1, df2, on="ID", how="inner")

   ID Name  Salary
0   3    C   30000
1   4    D   40000

In [38]:
pd.merge(df1, df2, on="ID", how="left")

   ID Name   Salary
0   1    A      NaN
1   2    B      NaN
2   3    C  30000.0
3   4    D  40000.0

In [39]:
pd.merge(df1, df2, on="ID", how="right")

   ID Name  Salary
0   3    C   30000
1   4    D   40000
2   5  NaN   50000
3   6  NaN   60000

In [40]:
pd.merge(df1, df2, on="ID", how="outer")

   ID Name   Salary
0   1    A      NaN
1   2    B      NaN
2   3    C  30000.0
3   4    D  40000.0
4   5  NaN  50000.0
5   6  NaN  60000.0

In [41]:
pd.merge(df1, df2, on="ID", how="outer", indicator=True)

   ID Name   Salary      _merge
0   1    A      NaN   left_only
1   2    B      NaN   left_only
2   3    C  30000.0        both
3   4    D  40000.0        both
4   5  NaN  50000.0  right_only
5   6  NaN  60000.0  right_only

In [42]:
df3 = pd.DataFrame({
    "ID":[1,2,3,4],
    "Bonus":[1000,2000,3000,4000]
})

In [43]:
df3 = pd.DataFrame({
    "ID":[1,2,3,4],
    "Bonus":[1000,2000,3000,4000]
})

In [44]:
pd.concat([df1, df2], axis=1)

   ID Name  ID  Salary
0   1    A   3   30000
1   2    B   4   40000
2   3    C   5   50000
3   4    D   6   60000

In [45]:
pd.concat([df1, df2, df3], ignore_index=True)

    ID Name   Salary   Bonus
0    1    A      NaN     NaN
1    2    B      NaN     NaN
2    3    C      NaN     NaN
3    4    D      NaN     NaN
4    3  NaN  30000.0     NaN
5    4  NaN  40000.0     NaN
6    5  NaN  50000.0     NaN
7    6  NaN  60000.0     NaN
8    1  NaN      NaN  1000.0
9    2  NaN      NaN  2000.0
10   3  NaN      NaN  3000.0
11   4  NaN      NaN  4000.0

In [46]:
pd.concat([df1, df2], keys=["First", "Second"])

          ID Name   Salary
First  0   1    A      NaN
       1   2    B      NaN
       2   3    C      NaN
       3   4    D      NaN
Second 0   3  NaN  30000.0
       1   4  NaN  40000.0
       2   5  NaN  50000.0
       3   6  NaN  60000.0

In [47]:
pd.pivot_table(df,
               values="Sales",
               index="Region",
               aggfunc="sum")

        Sales
Region
East    75000
North   90000
South   90000
West    70000

In [48]:
pd.pivot_table(df,
               values="Sales",
               index="Region",
               columns="Product",
               aggfunc="sum")

Product  Laptop  Mobile  Tablet
Region
East      20000   15000   40000
North     20000   30000   40000
South     20000   30000   40000
West      20000   30000   20000

In [49]:
pd.pivot_table(df,
               values="Sales",
               index="Region",
               columns="Product",
               aggfunc="mean")

Product   Laptop   Mobile   Tablet
Region
East     10000.0  15000.0  20000.0
North    10000.0  15000.0  20000.0
South    10000.0  15000.0  20000.0
West     10000.0  15000.0  20000.0

In [50]:
df["Year"] = df["Date"].dt.year
df["Month"] = df["Date"].dt.month
df["Day"] = df["Date"].dt.day

In [51]:
df = df.set_index("Date")

df["Rolling_Avg"] = df["Sales"].rolling(3).mean()

In [52]:
df.groupby("Product")["Sales"].sum()

Product
Laptop     80000
Mobile    105000
Tablet    140000
Name: Sales, dtype: int64

In [53]:
df.loc[df.groupby("Region")["Sales"].idxmax()]

,Name,Age,Maths,Science,English,Computer,Percentage,Department,Employee,Salary,Experience,Region,Product,Sales,Year,Month,Day,Rolling_Avg
Date,,,,,,,,,,,,,,,,,,
2025-01-03,Prerana Sachin Veer,31.0,92,89,90.0,95.0,NaN,Sales,Prerana Sachin Veer,50000,3,East,Tablet,20000,2025,1,3,15000.0
2025-01-09,Pradnya Pramod Ghag,37.0,77,75,NaN,81.0,78.00,Sales,Pradnya Pramod Ghag,30000,4,North,Tablet,20000,2025,1,9,15000.0
2025-01-06,Anushka Nilesh Jadhav,33.0,81,79,83.0,85.0,82.00,Sales,Anushka Nilesh Jadhav,40000,1,South,Tablet,20000,2025,1,6,15000.0
2025-01-12,Pooja Vijay Lakhe,NaN,84,82,80.0,85.0,82.75,Sales,Pooja Vijay Lakhe,60000,2,West,Tablet,20000,2025,1,12,15000.0

In [54]:
customers = pd.DataFrame({
    "CustomerID":[1,2,3],
    "CustomerName":["Ram","Sham","Sita"]
})

orders = pd.DataFrame({
    "CustomerID":[1,2,3],
    "OrderAmount":[1000,2000,3000]
})

In [55]:
pd.merge(customers, orders, on="CustomerID")

   CustomerID CustomerName  OrderAmount
0           1          Ram         1000
1           2         Sham         2000
2           3         Sita         3000

In [56]:
jan = pd.DataFrame({"Sales":[1000,2000]})
feb = pd.DataFrame({"Sales":[1500,2500]})
mar = pd.DataFrame({"Sales":[1800,2800]})

pd.concat([jan, feb, mar], ignore_index=True)

   Sales
0   1000
1   2000
2   1500
3   2500
4   1800
5   2800

In [57]:
pd.pivot_table(df,
               values="Sales",
               index="Month",
               columns="Product",
               aggfunc="sum")

Product  Laptop  Mobile  Tablet
Month
1         80000  105000  140000

In [58]:
df.resample("W")["Sales"].sum()

Date
2025-01-05     70000
2025-01-12    110000
2025-01-19    100000
2025-01-26     45000
Freq: W-SUN, Name: Sales, dtype: int64

In [59]:
df["Cumulative_Sales"] = df["Sales"].cumsum()
df[["Sales","Cumulative_Sales"]]

            Sales  Cumulative_Sales
Date
2025-01-01  10000             10000
2025-01-02  15000             25000
2025-01-03  20000             45000
2025-01-04  10000             55000
2025-01-05  15000             70000
2025-01-06  20000             90000
2025-01-07  10000            100000
2025-01-08  15000            115000
2025-01-09  20000            135000
2025-01-10  10000            145000
2025-01-11  15000            160000
2025-01-12  20000            180000
2025-01-13  10000            190000
2025-01-14  15000            205000
2025-01-15  20000            225000
2025-01-16  10000            235000
2025-01-17  15000            250000
2025-01-18  20000            270000
2025-01-19  10000            280000
2025-01-20  15000            295000
2025-01-21  20000            315000
2025-01-22  10000            325000

In [60]:
df.groupby("Department")["Salary"] \
  .mean() \
  .sort_values(ascending=False) \
  .head(3)

Department
IT       45000.000000
HR       44285.714286
Sales    42857.142857
Name: Salary, dtype: float64

In [61]:
pd.merge(pd.merge(df1, df2, on="ID"), df3, on="ID")

   ID Name  Salary  Bonus
0   3    C   30000   3000
1   4    D   40000   4000

In [62]:
pd.pivot_table(df,
               values="Sales",
               index="Region",
               columns="Product",
               aggfunc=["sum","mean","count"])

           sum                   mean                    count
Product Laptop Mobile Tablet   Laptop   Mobile   Tablet Laptop Mobile Tablet
Region
East     20000  15000  40000  10000.0  15000.0  20000.0      2      1      2
North    20000  30000  40000  10000.0  15000.0  20000.0      2      2      2
South    20000  30000  40000  10000.0  15000.0  20000.0      2      2      2
West     20000  30000  20000  10000.0  15000.0  20000.0      2      2      1

In [64]:
import pandas as pd

pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

print(df)

                                 Name   Age  Maths  Science  English  \
Date
2025-01-01            Avani Chaudhari  32.0     85       88     82.0
2025-01-02    Shravani Goraksha Sukre  34.0     78       80     75.0
2025-01-03        Prerana Sachin Veer  31.0     92       89     90.0
2025-01-04       Shreya Tanaji Jadhav  35.0     70       72     74.0
2025-01-05         Ashwin Nitin Dhake  38.0     88       85     84.0
2025-01-06      Anushka Nilesh Jadhav  33.0     81       79     83.0
2025-01-07          Sarthak Darandale  36.0     65       68     70.0
2025-01-08          Riya Vijay Sawant  30.0     95       93     94.0
2025-01-09        Pradnya Pramod Ghag  37.0     77       75      NaN
2025-01-10  Samruddhi Vinod Talagatti  34.0     89       87     90.0
2025-01-11        Srushti Anand Dhoka  32.0     73       76     78.0
2025-01-12          Pooja Vijay Lakhe   NaN     84       82     80.0
2025-01-13     Sailee Pandit Hingmire  31.0     91       92     88.0
2025-01-14  Yashshri Prashant Tembare  35.0     69       71     73.0
2025-01-15     Shravani Rajesh Jadhav  33.0     87       85     86.0
2025-01-16            Tanishka Gawade  36.0     74       78     76.0
2025-01-17     Leena Ramesh Ghumatkar  30.0     93       91     92.0
2025-01-18        Archita Ankur Dhoka  38.0     80       82     84.0
2025-01-19  Samruddhi Dattatray Gorde  34.0     72       74     76.0
2025-01-20        Mrunali Nilesh Kore  37.0     86       88     87.0
2025-01-21  Mangesh Vijaykumar Ghodke  40.0     68       70     72.0
2025-01-22              Amruta Gawade  32.0     90       89     91.0

            Computer  Percentage Department                   Employee  \
Date
2025-01-01      90.0       86.25         IT            Avani Chaudhari
2025-01-02      82.0       78.75         HR    Shravani Goraksha Sukre
2025-01-03      95.0         NaN      Sales        Prerana Sachin Veer
2025-01-04      76.0       73.00         IT       Shreya Tanaji Jadhav
2025-01-05       NaN       86.50         HR         Ashwin Nitin Dhake
2025-01-06      85.0       82.00      Sales      Anushka Nilesh Jadhav
2025-01-07      72.0       68.75         IT          Sarthak Darandale
2025-01-08      96.0       94.50         HR          Riya Vijay Sawant
2025-01-09      81.0       78.00      Sales        Pradnya Pramod Ghag
2025-01-10      91.0       89.25         IT  Samruddhi Vinod Talagatti
2025-01-11      80.0       76.75         HR        Srushti Anand Dhoka
2025-01-12      85.0       82.75      Sales          Pooja Vijay Lakhe
2025-01-13      94.0       91.25         IT     Sailee Pandit Hingmire
2025-01-14      75.0       72.00         HR  Yashshri Prashant Tembare
2025-01-15      88.0       86.50      Sales     Shravani Rajesh Jadhav
2025-01-16      79.0       76.75         IT            Tanishka Gawade
2025-01-17      95.0       92.75         HR     Leena Ramesh Ghumatkar
2025-01-18      86.0       83.00      Sales        Archita Ankur Dhoka
2025-01-19      78.0       75.00         IT  Samruddhi Dattatray Gorde
2025-01-20      89.0       87.50         HR        Mrunali Nilesh Kore
2025-01-21      74.0         NaN      Sales  Mangesh Vijaykumar Ghodke
2025-01-22      93.0       90.75         IT              Amruta Gawade

            Salary  Experience Region Product  Sales  Year  Month  Day  \
Date
2025-01-01   30000           1  North  Laptop  10000  2025      1    1
2025-01-02   40000           2  South  Mobile  15000  2025      1    2
2025-01-03   50000           3   East  Tablet  20000  2025      1    3
2025-01-04   60000           4   West  Laptop  10000  2025      1    4
2025-01-05   30000           5  North  Mobile  15000  2025      1    5
2025-01-06   40000           1  South  Tablet  20000  2025      1    6
2025-01-07   50000           2   East  Laptop  10000  2025      1    7
2025-01-08   60000           3   West  Mobile  15000  2025      1    8
2025-01-09   30000           4  North  Tablet  20000  2025      1    9
2025-01-10   40000           5  South  Laptop  10000  2025      1   10
2025-01-11   50000           1   East  Mobile  15000  2025      1   11
2025-01-12   60000           2   West  Tablet  20000  2025      1   12
2025-01-13   30000           3  North  Laptop  10000  2025      1   13
2025-01-14   40000           4  South  Mobile  15000  2025      1   14
2025-01-15   50000           5   East  Tablet  20000  2025      1   15
2025-01-16   60000           1   West  Laptop  10000  2025      1   16
2025-01-17   30000           2  North  Mobile  15000  2025      1   17
2025-01-18   40000           3  South  Tablet  20000  2025      1   18
2025-01-19   50000           4   East  Laptop  10000  2025      1   19
2025-01-20   60000           5   West  Mobile  15000  2025      1   20
2025-01-21   30000           1  North  Tablet  20000  2025      1   21
2025-01-22   40000           2  South  Laptop  10000  2025      1   22

            Rolling_Avg  Cumulative_Sales
Date
2025-01-01          NaN             10000
2025-01-02          NaN             25000
2025-01-03      15000.0             45000
2025-01-04      15000.0             55000
2025-01-05      15000.0             70000
2025-01-06      15000.0             90000
2025-01-07      15000.0            100000
2025-01-08      15000.0            115000
2025-01-09      15000.0            135000
2025-01-10      15000.0            145000
2025-01-11      15000.0            160000
2025-01-12      15000.0            180000
2025-01-13      15000.0            190000
2025-01-14      15000.0            205000
2025-01-15      15000.0            225000
2025-01-16      15000.0            235000
2025-01-17      15000.0            250000
2025-01-18      15000.0            270000
2025-01-19      15000.0            280000
2025-01-20      15000.0            295000
2025-01-21      15000.0            315000
2025-01-22      15000.0            325000

In [65]:
df.groupby("Department")["Salary"].mean()

Department
HR       44285.714286
IT       45000.000000
Sales    42857.142857
Name: Salary, dtype: float64

In [66]:
df.groupby("Department")["Salary"].max()

Department
HR       60000
IT       60000
Sales    60000
Name: Salary, dtype: int64

In [67]:
df.groupby("Department")["Salary"].sum()

Department
HR       310000
IT       360000
Sales    300000
Name: Salary, dtype: int64

In [68]:
df.groupby("Department")["Employee"].count()

Department
HR       7
IT       8
Sales    7
Name: Employee, dtype: int64

In [69]:
df.groupby("Department")[["Salary","Experience"]].mean()

                  Salary  Experience
Department
HR          44285.714286    3.142857
IT          45000.000000    2.750000
Sales       42857.142857    2.714286

In [70]:
pd.merge(df1, df2, on="ID", how="inner")

   ID Name  Salary
0   3    C   30000
1   4    D   40000

In [71]:
pd.merge(df1, df2, on="ID", how="left")

   ID Name   Salary
0   1    A      NaN
1   2    B      NaN
2   3    C  30000.0
3   4    D  40000.0

In [72]:
pd.merge(df1, df2, on="ID", how="right")

   ID Name  Salary
0   3    C   30000
1   4    D   40000
2   5  NaN   50000
3   6  NaN   60000

In [73]:
pd.merge(df1, df2, on="ID", how="outer")

   ID Name   Salary
0   1    A      NaN
1   2    B      NaN
2   3    C  30000.0
3   4    D  40000.0
4   5  NaN  50000.0
5   6  NaN  60000.0

In [74]:
pd.merge(df1, df2, on="ID", how="outer", indicator=True)\
.query('_merge != "both"')

   ID Name   Salary      _merge
0   1    A      NaN   left_only
1   2    B      NaN   left_only
4   5  NaN  50000.0  right_only
5   6  NaN  60000.0  right_only

In [75]:
pd.concat([df1, df2], axis=0)

   ID Name   Salary
0   1    A      NaN
1   2    B      NaN
2   3    C      NaN
3   4    D      NaN
0   3  NaN  30000.0
1   4  NaN  40000.0
2   5  NaN  50000.0
3   6  NaN  60000.0

In [76]:
pd.concat([df1, df2], axis=1)

   ID Name  ID  Salary
0   1    A   3   30000
1   2    B   4   40000
2   3    C   5   50000
3   4    D   6   60000

In [77]:
pd.concat([df1, df2, df3], ignore_index=True)

    ID Name   Salary   Bonus
0    1    A      NaN     NaN
1    2    B      NaN     NaN
2    3    C      NaN     NaN
3    4    D      NaN     NaN
4    3  NaN  30000.0     NaN
5    4  NaN  40000.0     NaN
6    5  NaN  50000.0     NaN
7    6  NaN  60000.0     NaN
8    1  NaN      NaN  1000.0
9    2  NaN      NaN  2000.0
10   3  NaN      NaN  3000.0
11   4  NaN      NaN  4000.0

In [78]:
pd.concat([df1, df2], keys=["First","Second"])

          ID Name   Salary
First  0   1    A      NaN
       1   2    B      NaN
       2   3    C      NaN
       3   4    D      NaN
Second 0   3  NaN  30000.0
       1   4  NaN  40000.0
       2   5  NaN  50000.0
       3   6  NaN  60000.0

In [79]:
pd.pivot_table(
    df,
    values="Sales",
    index="Region",
    aggfunc="sum"
)

        Sales
Region
East    75000
North   90000
South   90000
West    70000

In [80]:
pd.pivot_table(
    df,
    values="Sales",
    index="Region",
    columns="Product",
    aggfunc="sum"
)

Product  Laptop  Mobile  Tablet
Region
East      20000   15000   40000
North     20000   30000   40000
South     20000   30000   40000
West      20000   30000   20000

In [81]:
pd.pivot_table(
    df,
    values="Sales",
    index="Region",
    columns="Product",
    aggfunc="mean"
)

Product   Laptop   Mobile   Tablet
Region
East     10000.0  15000.0  20000.0
North    10000.0  15000.0  20000.0
South    10000.0  15000.0  20000.0
West     10000.0  15000.0  20000.0

In [86]:
df["Date"] = pd.to_datetime(df["Date"])

In [87]:
df["Year"] = df["Date"].dt.year
df["Month"] = df["Date"].dt.month
df["Day"] = df["Date"].dt.day

In [88]:
df.set_index("Date", inplace=True)
df["Rolling_Avg"] = df["Sales"].rolling(3).mean()

In [89]:
df.groupby("Product")["Sales"].sum()

Product
Laptop     80000
Mobile    105000
Tablet    140000
Name: Sales, dtype: int64

In [90]:
df.loc[df.groupby("Region")["Sales"].idxmax()]

,Name,Age,Maths,Science,English,Computer,Percentage,Department,Employee,Salary,Experience,Region,Product,Sales,Year,Month,Day,Rolling_Avg,Cumulative_Sales
Date,,,,,,,,,,,,,,,,,,,
2025-01-03,Prerana Sachin Veer,31.0,92,89,90.0,95.0,NaN,Sales,Prerana Sachin Veer,50000,3,East,Tablet,20000,2025,1,3,15000.0,45000
2025-01-09,Pradnya Pramod Ghag,37.0,77,75,NaN,81.0,78.00,Sales,Pradnya Pramod Ghag,30000,4,North,Tablet,20000,2025,1,9,15000.0,135000
2025-01-06,Anushka Nilesh Jadhav,33.0,81,79,83.0,85.0,82.00,Sales,Anushka Nilesh Jadhav,40000,1,South,Tablet,20000,2025,1,6,15000.0,90000
2025-01-12,Pooja Vijay Lakhe,NaN,84,82,80.0,85.0,82.75,Sales,Pooja Vijay Lakhe,60000,2,West,Tablet,20000,2025,1,12,15000.0,180000

In [91]:
pd.merge(customers, orders, on="CustomerID")

   CustomerID CustomerName  OrderAmount
0           1          Ram         1000
1           2         Sham         2000
2           3         Sita         3000

In [92]:
pd.concat([jan, feb, mar], ignore_index=True)

   Sales
0   1000
1   2000
2   1500
3   2500
4   1800
5   2800

In [93]:
pd.pivot_table(
    df,
    values="Sales",
    index="Month",
    columns="Product",
    aggfunc="sum"
)

Product  Laptop  Mobile  Tablet
Month
1         80000  105000  140000

In [94]:
df.resample("W")["Sales"].sum()

Date
2025-01-05     70000
2025-01-12    110000
2025-01-19    100000
2025-01-26     45000
Freq: W-SUN, Name: Sales, dtype: int64

In [95]:
df["Cumulative_Sales"] = df["Sales"].cumsum()

In [96]:
df.groupby("Department")["Salary"] \
  .mean() \
  .sort_values(ascending=False) \
  .head(3)

Department
IT       45000.000000
HR       44285.714286
Sales    42857.142857
Name: Salary, dtype: float64

In [97]:
df.groupby("Department")["Salary"] \
  .mean() \
  .sort_values(ascending=False) \
  .head(3)

Department
IT       45000.000000
HR       44285.714286
Sales    42857.142857
Name: Salary, dtype: float64

In [98]:
pd.merge(
    pd.merge(df1, df2, on="ID"),
    df3,
    on="ID"
)

   ID Name  Salary  Bonus
0   3    C   30000   3000
1   4    D   40000   4000

In [99]:
pd.pivot_table(
    df,
    values="Sales",
    index="Region",
    columns="Product",
    aggfunc=["sum", "mean", "count"]
)

           sum                   mean                    count
Product Laptop Mobile Tablet   Laptop   Mobile   Tablet Laptop Mobile Tablet
Region
East     20000  15000  40000  10000.0  15000.0  20000.0      2      1      2
North    20000  30000  40000  10000.0  15000.0  20000.0      2      2      2
South    20000  30000  40000  10000.0  15000.0  20000.0      2      2      2
West     20000  30000  20000  10000.0  15000.0  20000.0      2      2      1