In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
list = ["salim","shubham","ashwin","sarthak","Mangesh"]
list

['salim', 'shubham', 'ashwin', 'sarthak']

In [8]:
a = pd.Series(list)
a[2]

'ashwin'

In [9]:
label = ['a','b','c','d']

In [10]:
a = pd.Series(list,index=label)
a

a      salim
b    shubham
c     ashwin
d    sarthak
dtype: object

In [11]:
arr = np.array(['india','japan','china','USA'])
arr

array(['india', 'japan', 'china', 'USA'], dtype='<U5')

In [12]:
b = pd.Series(arr)
b

0    india
1    japan
2    china
3      USA
dtype: object

In [13]:
label = ['country1','country2','country3','country4']

In [16]:
b = pd.Series(arr,index=label)
b

country1    india
country2    japan
country3    china
country4      USA
dtype: object

In [39]:
import pandas as pd

data = {
    'Name': ['Mangesh', 'Ashwin', 'Sarthak', 'pradnya'],
    'Age': [20, 21, 19, 17],
    'City': ['Pune', 'Jalgaon', 'nashik', 'Nagpur'],
    'country':['india','japan','china','USA'],
    'salary' : [2000, 3000, 2300, 2345],
}

data

{'Name': ['Mangesh', 'Ashwin', 'Sarthak', 'pradnya'],
 'Age': [20, 21, 19, 17],
 'City': ['Pune', 'Jalgaon', 'nashik', 'Nagpur'],
 'country': ['india', 'japan', 'china', 'USA'],
 'salary': [2000, 3000, 2300, 2345]}

In [40]:
d = pd.DataFrame(data)
d

      Name  Age     City country  salary
0  Mangesh   20     Pune   india    2000
1   Ashwin   21  Jalgaon   japan    3000
2  Sarthak   19   nashik   china    2300
3  pradnya   17   Nagpur     USA    2345

In [41]:
a

a      salim
b    shubham
c     ashwin
d    sarthak
dtype: object

In [42]:
b

country1    india
country2    japan
country3    china
country4      USA
dtype: object

In [43]:
d

      Name  Age     City country  salary
0  Mangesh   20     Pune   india    2000
1   Ashwin   21  Jalgaon   japan    3000
2  Sarthak   19   nashik   china    2300
3  pradnya   17   Nagpur     USA    2345

In [44]:
df = pd.Series(data)

In [45]:
df

Name       [Mangesh, Ashwin, Sarthak, pradnya]
Age                           [20, 21, 19, 17]
City           [Pune, Jalgaon, nashik, Nagpur]
country             [india, japan, china, USA]
salary                [2000, 3000, 2300, 2345]
dtype: object

In [46]:
list = ["Name","age","city","salary"]

In [47]:
list

['Name', 'age', 'city', 'salary']

In [51]:
a = pd.DataFrame(data,columns=[ ["Name","age","city","salary"]])
a

Empty DataFrame
Columns: [(Name,), (age,), (city,), (salary,)]
Index: []

In [52]:
df

Name       [Mangesh, Ashwin, Sarthak, pradnya]
Age                           [20, 21, 19, 17]
City           [Pune, Jalgaon, nashik, Nagpur]
country             [india, japan, china, USA]
salary                [2000, 3000, 2300, 2345]
dtype: object

In [55]:
df = pd.DataFrame(data)

In [56]:
df

      Name  Age     City country  salary
0  Mangesh   20     Pune   india    2000
1   Ashwin   21  Jalgaon   japan    3000
2  Sarthak   19   nashik   china    2300
3  pradnya   17   Nagpur     USA    2345

In [71]:
df["Name"]

0    Mangesh
1     Ashwin
2    Sarthak
3    pradnya
Name: Name, dtype: object

In [72]:
df[["Name","Age"]]

      Name  Age
0  Mangesh   20
1   Ashwin   21
2  Sarthak   19
3  pradnya   17

In [78]:
df

      Name  Age     City country  salary
0  Mangesh   20     Pune   india    2000
1   Ashwin   21  Jalgaon   japan    3000
2  Sarthak   19   nashik   china    2300
3  pradnya   17   Nagpur     USA    2345

## df.iloc[[0,1]]

In [88]:
d.loc[[0,1],[["city","salary"]]

_IncompleteInputError: incomplete input (782643570.py, line 1)

In [99]:
d[(d["age"] > 19) & (d["city"] == "pune"])

SyntaxError: closing parenthesis ']' does not match opening parenthesis '(' (1744272657.py, line 1)